### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Axkaban** [CarlosSengo/dasmoto-art#1]
Great job having [comments!](https://github.com/CarlosSengo/dasmoto-art/blob/master/index.html#L16) 

Also really nice choice to have [strong](https://github.com/CarlosSengo/dasmoto-art/blob/master/index.html#L27) tags to separate the text in the paragraph. Another way to achieve that is by using span tags! in case you need to do other changes besides making the text bold, span tags might be the way to go.

Great work also saving your resources locally and using their file path, as well as giving img tags an alt attribute. Bravo!

**Comment by CarlosSengo** [comment]
Thanks Axel!! Regarding <span> tag, the purpose was to make the last sentence in the paragraphs bold, however it became redundant when I then applied bold again on CSS file. Will keep that in mind. Many thanks for your feedback, well appreciated! coding everyday really helps to improve my skills.
