### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Axkaban** [CarlosSengo/dasmoto-art#2]
Again, thank you for the [comments!](https://github.com/CarlosSengo/dasmoto-art/blob/master/css/main.css#L1)

Since the purpose of a strong tag is to turn text's font weight into bold, you do not need to [assign](https://github.com/CarlosSengo/dasmoto-art/blob/master/css/main.css#L10) that in the css file. You would've had to if it was a span tag.

Those elements that share the [same styles ](https://github.com/CarlosSengo/dasmoto-art/blob/master/css/main.css#L33-L34)can be grouped so you won't have to repeat the same properties and values over and over:
```
.header-one,
.header-two,
.header-three{
    font-size: 32px;
    font-weight: bold;
}
```
Also remember to space them on a new line after each comma, it makes it for easier, better readability on the developer side.

**Comment by CarlosSengo** [comment]
indeed its redundant as I used <strong> tag in HTML, will keep it in mind, thanks!
